name: flutter_one_of
description: A Flutter package that provides utility classes for working with algebraic data types (ADTs) known as "one-of" types. These types allow you to represent a value that can be one of several possible options.
version: 0.0.1
homepage: https://pub.dev/publishers/zooper.dev/packages

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
